//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public decimal id { get; set; }
        public string principal { get; set; }
        public string password { get; set; }
        public string account1 { get; set; }
        public string principal_mobile { get; set; }
        public string status { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public Nullable<int> level { get; set; }
        public string district_name { get; set; }
        public string xzjd_name { get; set; }
        public string cyd_name { get; set; }
        public string jcd_name { get; set; }
        public string serial_no { get; set; }
    }
}
