//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class attendance
    {
        public long id { get; set; }
        public string morn_office_time { get; set; }
        public string morn_closing_time { get; set; }
        public string after_office_time { get; set; }
        public string after_closing_time { get; set; }
        public Nullable<int> advance_office_clock { get; set; }
        public Nullable<int> allow_late { get; set; }
        public Nullable<int> duty { get; set; }
        public Nullable<int> allow_advance_closing { get; set; }
        public Nullable<int> advance_closing { get; set; }
        public Nullable<int> leave_duty { get; set; }
        public Nullable<int> overtime { get; set; }
        public Nullable<int> overtime_mins { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
    }
}
