//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public long id { get; set; }
        public Nullable<long> employee_id { get; set; }
        public Nullable<int> work_type { get; set; }
        public Nullable<int> business_type { get; set; }
        public string status { get; set; }
        public string photo { get; set; }
        public string apply_day { get; set; }
        public string amount { get; set; }
        public string description { get; set; }
        public string start_time { get; set; }
        public string attendance_day { get; set; }
        public string end_time { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public string addr { get; set; }
        public string longitude { get; set; }
        public string latitude { get; set; }
        public string duplicaters { get; set; }
        public Nullable<int> is_read { get; set; }
    }
}
