//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientdetails
    {
        public string appId { get; set; }
        public string resourceIds { get; set; }
        public string appSecret { get; set; }
        public string scope { get; set; }
        public string grantTypes { get; set; }
        public string redirectUrl { get; set; }
        public string authorities { get; set; }
        public Nullable<int> access_token_validity { get; set; }
        public Nullable<int> refresh_token_validity { get; set; }
        public string additionalInformation { get; set; }
        public string autoApproveScopes { get; set; }
    }
}
