//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class code_info
    {
        public string id { get; set; }
        public string employee_no { get; set; }
        public string mffd { get; set; }
        public string mzt { get; set; }
        public string mlx { get; set; }
        public string hmcmyy { get; set; }
        public string scffsj { get; set; }
        public string scsqsj { get; set; }
        public string zjgxsj { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
    }
}
