//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class cyd_tab
    {
        public long id { get; set; }
        public string xzjd_name { get; set; }
        public string xzjd_number { get; set; }
        public string cyd_name { get; set; }
        public string unit { get; set; }
        public string cyd_number { get; set; }
        public string jcd_name { get; set; }
        public string district_name { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<sbyte> is_deleted { get; set; }
    }
}
