//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaceContext : DbContext
    {
        public FaceContext()
            : base("name=FaceContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<access_permission_group> access_permission_group { get; set; }
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<attendance> attendance { get; set; }
        public virtual DbSet<business> business { get; set; }
        public virtual DbSet<carbon> carbon { get; set; }
        public virtual DbSet<clientdetails> clientdetails { get; set; }
        public virtual DbSet<code_info> code_info { get; set; }
        public virtual DbSet<cyd_tab> cyd_tab { get; set; }
        public virtual DbSet<department> department { get; set; }
        public virtual DbSet<device> device { get; set; }
        public virtual DbSet<device_channel> device_channel { get; set; }
        public virtual DbSet<device_permission_group_rel> device_permission_group_rel { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<employee_attendance> employee_attendance { get; set; }
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<equipment_employee> equipment_employee { get; set; }
        public virtual DbSet<expenseinfo> expenseinfo { get; set; }
        public virtual DbSet<facility> facility { get; set; }
        public virtual DbSet<flow> flow { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<oauth_access_token> oauth_access_token { get; set; }
        public virtual DbSet<oauth_client_details> oauth_client_details { get; set; }
        public virtual DbSet<oauth_client_token> oauth_client_token { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<person> person { get; set; }
        public virtual DbSet<person_card> person_card { get; set; }
        public virtual DbSet<person_permission_group_rel> person_permission_group_rel { get; set; }
        public virtual DbSet<problem> problem { get; set; }
        public virtual DbSet<record> record { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<staff> staff { get; set; }
        public virtual DbSet<staff_health_code> staff_health_code { get; set; }
        public virtual DbSet<staff_nucleic_acid> staff_nucleic_acid { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_permission_relation> user_permission_relation { get; set; }
    }
}
