//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class device_channel
    {
        public string channel_id { get; set; }
        public string channel_name { get; set; }
        public string channel_type { get; set; }
        public Nullable<int> channel_no { get; set; }
        public string channel_status { get; set; }
        public string device_serial { get; set; }
    }
}
