//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class device
    {
        public string device_id { get; set; }
        public string device_serial { get; set; }
        public string device_model { get; set; }
        public string device_status { get; set; }
        public string device_name { get; set; }
        public string validate_code { get; set; }
        public string group_id { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
    }
}
