//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public decimal id { get; set; }
        public string employee_name { get; set; }
        public string employee_code { get; set; }
        public string employee_card { get; set; }
        public string mobile { get; set; }
        public string employee_status { get; set; }
        public string created { get; set; }
        public string updated { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public Nullable<int> is_check { get; set; }
        public string department_name { get; set; }
        public Nullable<long> department_id { get; set; }
        public string photo { get; set; }
        public string board_date { get; set; }
        public string card_type_name { get; set; }
        public string card_type { get; set; }
        public string card_no { get; set; }
        public string start_day { get; set; }
        public string end_day { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public string department_no { get; set; }
        public string password { get; set; }
        public Nullable<int> sex { get; set; }
        public string birthday { get; set; }
    }
}
