//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_attendance
    {
        public decimal id { get; set; }
        public string employee_name { get; set; }
        public string employee_code { get; set; }
        public string department_name { get; set; }
        public Nullable<long> department_id { get; set; }
        public string office_time { get; set; }
        public string office_card { get; set; }
        public Nullable<int> office_state { get; set; }
        public string closing_time { get; set; }
        public string closing_card { get; set; }
        public Nullable<int> closing_state { get; set; }
        public Nullable<int> leavetimes { get; set; }
        public Nullable<int> latetimes { get; set; }
        public string created { get; set; }
        public string updated { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string attendance_day { get; set; }
    }
}
