//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment
    {
        public long id { get; set; }
        public string equipment_name { get; set; }
        public string equipment_no { get; set; }
        public string area { get; set; }
        public string protocol { get; set; }
        public string code { get; set; }
        public string ip_address { get; set; }
        public string port { get; set; }
        public string equipment_serial_no { get; set; }
        public string account { get; set; }
        public string password { get; set; }
        public string district { get; set; }
        public string network { get; set; }
        public string description { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<sbyte> type { get; set; }
    }
}
