//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_employee
    {
        public long id { get; set; }
        public Nullable<long> equipment_id { get; set; }
        public string equipment_name { get; set; }
        public string equipment_no { get; set; }
        public Nullable<long> employee_id { get; set; }
        public string employee_name { get; set; }
        public string employee_code { get; set; }
        public string employee_card { get; set; }
        public string mobile { get; set; }
        public string department_name { get; set; }
        public Nullable<long> department_id { get; set; }
        public string photo { get; set; }
        public string board_date { get; set; }
        public string card_type_name { get; set; }
        public string card_type { get; set; }
        public string card_no { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<int> is_check { get; set; }
        public string device_serial { get; set; }
    }
}
