//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class flow
    {
        public long id { get; set; }
        public Nullable<long> business_id { get; set; }
        public string prev_employee_id { get; set; }
        public string curr_employee_id { get; set; }
        public string description { get; set; }
        public Nullable<int> state { get; set; }
        public Nullable<int> is_agree { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<int> is_curr { get; set; }
        public string business_state { get; set; }
        public Nullable<int> is_read { get; set; }
    }
}
