//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class group
    {
        public string group_id { get; set; }
        public string group_no { get; set; }
        public string group_name { get; set; }
        public string parent_id { get; set; }
        public string path { get; set; }
    }
}
