//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_access_token
    {
        public string token_id { get; set; }
        public byte[] token { get; set; }
        public string authentication_id { get; set; }
        public string user_name { get; set; }
        public string client_id { get; set; }
        public byte[] authentication { get; set; }
        public string refresh_token { get; set; }
    }
}
