//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class oauth_client_details
    {
        public string client_id { get; set; }
        public string resource_ids { get; set; }
        public string client_secret { get; set; }
        public string scope { get; set; }
        public string authorized_grant_types { get; set; }
        public string web_server_redirect_uri { get; set; }
        public string authorities { get; set; }
        public Nullable<int> access_token_validity { get; set; }
        public Nullable<int> refresh_token_validity { get; set; }
        public string additional_information { get; set; }
        public string autoapprove { get; set; }
    }
}
