//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_nucleic_acid
    {
        public long id { get; set; }
        public string acid_no { get; set; }
        public string card_no { get; set; }
        public string serial_number { get; set; }
        public string company { get; set; }
        public string user_name { get; set; }
        public Nullable<sbyte> sex { get; set; }
        public string home_address { get; set; }
        public string address { get; set; }
        public Nullable<sbyte> testing_value { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<long> update_by { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<sbyte> is_deleted { get; set; }
        public string position { get; set; }
        public string detection_name { get; set; }
        public string update_name { get; set; }
        public string jcd_name { get; set; }
    }
}
