//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff_health_code
    {
        public long id { get; set; }
        public Nullable<long> equipment_id { get; set; }
        public Nullable<long> staff_id { get; set; }
        public string health_code { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public string temperature { get; set; }
        public string staff_name { get; set; }
        public string staff_code { get; set; }
        public string equipment_no { get; set; }
        public string staff_card { get; set; }
        public Nullable<int> sex { get; set; }
        public string area { get; set; }
        public string district { get; set; }
    }
}
