//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleic_Acid.Util
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public decimal id { get; set; }
        public string real_name { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string user_code { get; set; }
        public string mobile { get; set; }
        public string role_name { get; set; }
        public string role { get; set; }
        public string user_status { get; set; }
        public Nullable<int> is_deleted { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public Nullable<long> create_by { get; set; }
        public Nullable<long> update_by { get; set; }
        public string create_name { get; set; }
    }
}
